### ISSUE TITLE
too many files missing

### ISSUE THREAD

**Issue by Mrinal18** [woodfrog/ActionRecognition#4]
hello, i am finding difficulty in running the programe. i am running train_cnn.py / train_rnn.py 

Traceback (most recent call last):
  File "train_CNN.py", line 70, in <module>
    fit_model(model, train_data, test_data, weights_dir, input_shape)
  File "train_CNN.py", line 45, in fit_model
    callbacks=[checkpointer, tensorboard, earlystopping]
  File "C:\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "C:\Python36\lib\site-packages\keras\utils\data_utils.py", line 793, in get
    six.reraise(value._class_, value, value._traceback__)
  File "C:\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python36\lib\site-packages\keras\utils\data_utils.py", line 658, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\jigne\Desktop\BE PROJECT FILES\ActionRecognition\utils\UCF_utils.py", line 60, in image_from_sequence_generator
    batch_video, batch_label = next(video_gen)
  File "C:\Users\jigne\Desktop\BE PROJECT FILES\ActionRecognition\utils\UCF_utils.py", line 39, in sequence_generator
    raise FileExistsError('Too many file missing')
FileExistsError: Too many file missing

**Comment by ramnamaqsood776** [comment]
Hello 
I am having the same issue have you find out any solution for this?

**Comment by Aiiiiii** [comment]
Any solutions?

**Comment by Aiiiiii** [comment]
> Any solutions?

Oh I misname the data folder name. It solved.

**Comment by Zemin-Arzch** [comment]
> > Any solutions?
> 
> Oh I misname the data folder name. It solved.

Can you explain in detail
